version: "3.8"          

services:
  myportfolio:               
    container_name: myportfolio
    build: .                 
    restart: always          
    env_file:
      - .env                
    environment:
      - FLASK_ENV=development 
    ports:
      - "5001:5000"         
    volumes:
      - ./:/myportfolio     
    depends_on:
      - mysql              

  mysql:                    
    container_name: mysql
    image: mariadb:10.5     
    restart: always
    env_file:
      - .env               
    volumes:
      - mydatabase:/var/lib/mysql  

volumes:
  mydatabase:                